---
network:
    bonds:
        bond0:
            dhcp4: true
            dhcp4-overrides:
                route-metric: 500
            interfaces:
            - eno1
            - eno2
            - eno3
            - eno4
            parameters:
                lacp-rate: fast
                mode: 802.3ad
                transmit-hash-policy: layer2+3
    ethernets:
        eno1: {}
        eno2: {}
        eno3: {}
        eno4: {}
        eno49np0:
            mtu: 9000
        eno50np1:
            mtu: 9000
    version: 2
