---
dl380-1:
  lo_ip: "192.168.14.11"
  interface1: "eno49np0"
  interface2: "eno50np1"
  net: "49.0001.1111.1111.1111.00"
dl380-2:
  lo_ip: "192.168.14.12"
  interface1: "eno49np0"
  interface2: "eno50np1"
  net: "49.0001.2222.2222.2222.00"
dl380-3:
  lo_ip: "192.168.14.13"
  interface1: "eno49np0"
  interface2: "eno50np1"
  net: "49.0001.3333.3333.3333.00"
