---
- name: Manage /etc/hosts
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/frr_interfaces.yaml

  tasks:
    - name: Overwrite /etc/hosts with lo_ip entries
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
